# Generated by Django 6.0 on 2026-02-18 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Fortnightly Goal Review", max_length=255),
                ),
                ("meeting_date", models.DateField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("setup", "setup"),
                            ("nomination", "nomination"),
                            ("voting", "voting"),
                            ("results", "results"),
                            ("closed", "closed"),
                        ],
                        default="setup",
                        max_length=20,
                    ),
                ),
                ("recognition_period_start", models.DateField(blank=True, null=True)),
                ("recognition_period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["email"],
            },
        ),
    ]
