# Generated by Django 6.0 on 2026-02-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_nomination_vote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nomination",
            unique_together={("session", "nominator")},
        ),
        migrations.AddField(
            model_name="nomination",
            name="nominee_name",
            field=models.CharField(default="Self", max_length=255),
        ),
        migrations.RemoveField(
            model_name="nomination",
            name="nominee",
        ),
    ]
