# Generated by Django 6.0 on 2026-02-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0003_alter_nomination_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="vote",
            name="nomination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="recognition.nomination",
            ),
        ),
    ]
