# Generated by Django 6.0 on 2026-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0004_alter_vote_unique_together_alter_vote_nomination"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["name", "email"],
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
