# Generated by Django 6.0 on 2026-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0005_alter_participant_options_participant_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="voter",
        ),
        migrations.AlterUniqueTogether(
            name="nomination",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="meetingsession",
            name="recognition_period_end",
        ),
        migrations.RemoveField(
            model_name="meetingsession",
            name="recognition_period_start",
        ),
        migrations.RemoveField(
            model_name="meetingsession",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="nomination",
        ),
        migrations.AddField(
            model_name="meetingsession",
            name="winner_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="nominator_name",
            field=models.CharField(default="Legacy User", max_length=255),
        ),
        migrations.AddField(
            model_name="vote",
            name="nominations",
            field=models.ManyToManyField(blank=True, to="recognition.nomination"),
        ),
        migrations.AddField(
            model_name="vote",
            name="voter_name",
            field=models.CharField(default="Legacy User", max_length=255),
        ),
        migrations.AlterField(
            model_name="meetingsession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="meetingsession",
            name="meeting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meetingsession",
            name="phase",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("nomination", "Nomination"),
                    ("voting", "Voting"),
                    ("results", "Results"),
                    ("closed", "Closed"),
                ],
                default="setup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="nominee_name",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="nomination",
            name="nominator",
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
