# Generated by Django 6.0 on 2026-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0007_meetingsession_updated_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="nomination",
            constraint=models.UniqueConstraint(
                fields=("session", "nominator_name"),
                name="one_nomination_per_person_per_session",
            ),
        ),
    ]
