# Generated by Django 6.0 on 2026-02-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0008_one_nomination_per_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingsession",
            name="winner_name",
        ),
        migrations.AlterField(
            model_name="nomination",
            name="nominator_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter_name",
            field=models.CharField(max_length=255),
        ),
    ]
